### ISSUE TITLE
ZSTD_c_compressionLevel’ was not declared

### ISSUE THREAD

**Issue by qzane** [facebookresearch/vrs#80]
## Instructions To Reproduce the 🐛 Bug:
I'm trying to compile this on colab and here is the error I got
1. Full runnable code or full changes you made:

No change

2. What exact command you run:
``` shell
!mkdir /content/vrs/build
!cmake -S /content/vrs -B /content/vrs/build '-GCodeBlocks - Ninja'
!cd /content/vrs/build; ninja all; ninja install
```
4. **Full logs** or other relevant observations:

```
...
/content/vrs/vrs/Compressor.cpp:176:46: error: ‘ZSTD_c_compressionLevel’ was not declared in this scope
         ZSTD_CCtx_setParameter(zstdContext_, ZSTD_c_compressionLevel, compressionLevel));
                                                                        ^
```

5. please simplify the steps as much as possible so they do not require
   additional resources to run, such as a private dataset.

## Expected behavior:

No error

**Comment by georges-berenger** [comment]
This is a very strange error, because this declaration isn't new at all, neither in vrs or zstd. I have to assume that setup problem is happening. For "ZSTD_c_compressionLevel" to be not be declared, the header zstd.h must be corrupt, extremely outdated (over 4 years old, at least), or not found at all. Can you show the full set of errors, in particular what happened before?
Please check what version of zstd you have installed at the top of the zstd.h file, around the ZSTD_VERSION_MINOR symbol.

**Comment by qzane** [comment]
> This is a very strange error, because this declaration isn't new at all, neither in vrs or zstd. I have to assume that this is caused by some setup problem with the zstd library. For "ZSTD_c_compressionLevel" to be not be declared, the header zstd.h must be corrupt, extremely outdated (over 4 years old, at least), or not found at all. Can you show the full set of errors, in particular what happened before? Please check what version of zstd you have installed at the top of the zstd.h file, around the ZSTD_VERSION_MINOR symbol.

Yes, it seems that I didn't correctly install libzstd-dev, I'll look into that. BTW: do you have any suggestion about install that library on google colab? `apt install libzstd-dev` doesn't seems to be working.

**Comment by georges-berenger** [comment]
I don't have experience with google colab, sorry. In the meantime, I'll close this report.
